Add porting guide for HAL I2C API
ARMmbed/Handbook pull request #1103
Opened 2019-07-08 08:14 UTC by maciejbocianski

This is updated version of #807

@donatieng @jamesbeyond @MarceloSalazar @ashok-rao @AnotherButler 
please review

2019-07-09 21:30 UTC, AnotherButler approved these changes

2019-07-16 12:45 UTC, maciejbocianski commented
`i2c_set_clock_stretching` added, @AnotherButler please re-review

2019-07-17 18:31 UTC, AnotherButler approved these changes
Nice work 👍 Thanks for the PR.

2019-07-17 18:32 UTC, AnotherButler commented
ping @donatieng @jamesbeyond @MarceloSalazar @ashok-rao

2019-07-24 15:24 UTC, AnotherButler commented
ping @jamesbeyond @MarceloSalazar @ashok-rao @donatieng

2019-07-24 15:33 UTC, jamesbeyond requested changes
shall we added the warnings about: this new API is on a feature branch, not master.
just like: https://github.com/ARMmbed/mbed-os-5-docs/blob/development/docs/porting/target/spi.md#serial-peripheral-interface-spi
 
Otherwise it all looks good

2019-07-24 15:50 UTC, ashok-rao approved these changes
LGTM! Thanks!

2019-07-25 19:29 UTC, AnotherButler commented
@jamesbeyond Is this OK now?

2019-07-25 20:54 UTC, jamesbeyond approved these changes
Looks good , Thanks @AnotherButler

2019-07-25 21:12 UTC, merged