Update build recognition list in mbed_targets.md
ARMmbed/Handbook pull request #1131
Opened 2019-08-12 21:59 UTC by AnotherButler

Update list the build recognizes, as requested.

2019-08-19 09:04 UTC, 0xc0170 requested changes
What about `bootloader` feature, should it be in the list?

`lwip` feature was deprecated, should not be listed anymore

Isn't storage feature the one deprecated and we provide storage always?

cc @SeppoTakalo

2019-08-19 10:17 UTC, SeppoTakalo commented
This is the up to date list: https://github.com/ARMmbed/mbed-os/blob/master/tools/config/__init__.py#L72

From that list, `NANOSTACK` and `LWIP` are left there just to produce deprecation warning and not break the build. See: https://github.com/ARMmbed/mbed-os/tree/master/features/deprecated_warnings

`FEATURE_STORAGE` seems to have disappeared from some point. It doesn't do anything, so should be removed from list.


So, the list should be:
* BOOTLOADER
* BLE
* CRYPTOCELL310

2019-08-19 15:21 UTC, AnotherButler commented
Thanks for the help, @SeppoTakalo and @0xc0170  👍 Does that look better?

2019-08-20 13:43 UTC, 0xc0170 approved these changes

2019-08-20 18:56 UTC, merged