Clarify maximum timeout in Watchdog.md
ARMmbed/Handbook pull request #1134
Opened 2019-08-15 16:59 UTC by AnotherButler

Clarify line about maximum timeout to resolve issue #1133

2019-08-22 23:12 UTC, AnotherButler commented
ping @jamesbeyond @0xc0170

2019-08-23 08:56 UTC, 0xc0170 requested changes
otherwise LGTM

2019-08-23 08:56 UTC, 0xc0170 commented on docs/porting/target/Watchdog.md
> +- `UINT32_MAX` milliseconds is the maxinum allowed max_timeout `hal_watchdog_get_platform_features()` returns; minimum timeout is 1 ms.
`maxinum ` -> `maximum

2019-08-23 14:36 UTC, AnotherButler commented on docs/porting/target/Watchdog.md
> +- `UINT32_MAX` milliseconds is the maxinum allowed max_timeout `hal_watchdog_get_platform_features()` returns; minimum timeout is 1 ms.
😱 Good catch

2019-08-23 14:58 UTC, merged