Update links to examples
ARMmbed/Handbook pull request #1258
Opened 2020-03-02 13:50 UTC by mprse

Update links to the following examples:
- Platform,
- IO,
- RTOS,
- NFC,
- Network,
- Storage.

Related PR that brings example to https://github.com/ARMmbed/mbed-os-examples-docs_only: 
- https://github.com/ARMmbed/mbed-os-examples-docs_only/pull/70
- https://github.com/ARMmbed/mbed-os-examples-docs_only/pull/71
- https://github.com/ARMmbed/mbed-os-examples-docs_only/pull/75
- https://github.com/ARMmbed/mbed-os-examples-docs_only/pull/80

@AnotherButler Please review. Not sure if this is done in the correct way. I think we should wait with this one until the above list is merged.

2020-03-16 18:06 UTC, jamesbeyond commented
I believe all the code dependency been merged. could you review this PR @AnotherButler

2020-03-16 18:09 UTC, AnotherButler commented
For cellular, do we use the one in this PR or the official example, which should be kept up to date: https://github.com/ARMmbed/mbed-os-example-cellular/blob/mbed-os-5.15/main.cpp? @adbridge @jamesbeyond

2020-03-17 10:26 UTC, adbridge commented
@AnotherButler I think this is a question for @AnttiKauppila ?

2020-03-17 10:59 UTC, jamesbeyond approved these changes

2020-03-17 11:13 UTC, jamesbeyond commented
> For cellular, do we use the one in this PR or the official example, which should be kept up to date: https://github.com/ARMmbed/mbed-os-example-cellular/blob/mbed-os-5.15/main.cpp? @adbridge @jamesbeyond


the content of 
`https://github.com/ARMmbed/mbed-os-examples-docs_only/blob/master/APIs_NetworkInterfaces/Cellular/main.cpp` 
and 
`https://github.com/ARMmbed/mbed-os-example-cellular/blob/mbed-os-5.15/main.cpp` 
are identical. 


I agree to keep one, maybe `https://github.com/ARMmbed/mbed-os-example-cellular/blob/mbed-os-5.15/main.cpp` would be better

2020-03-17 11:18 UTC, jamesbeyond requested changes

2020-03-17 11:18 UTC, jamesbeyond commented on docs/api/networkinterfaces/CellularInterface.md
> +[![View code](https://www.mbed.com/embed/?url=github.com/ARMmbed/mbed-os-examples-docs_only/blob/master/APIs_NetworkInterfaces/Cellular/)](github.com/ARMmbed/mbed-os-examples-docs_only/blob/master/AP
@mprse could you change the link pointing to https://github.com/ARMmbed/mbed-os-example-cellular/blob/master/main.cpp

Don't worries about https://github.com/ARMmbed/mbed-os-examples-docs_only/tree/master/APIs_NetworkInterfaces/Cellular, I'll create a PR to remove that

2020-03-18 15:39 UTC, jamesbeyond commented on docs/api/networkinterfaces/CellularInterface.md
> +[![View code](https://www.mbed.com/embed/?url=github.com/ARMmbed/mbed-os-examples-docs_only/blob/master/APIs_NetworkInterfaces/Cellular/)](github.com/ARMmbed/mbed-os-examples-docs_only/blob/master/AP
```suggestion
[![View code](https://www.mbed.com/embed/?url=https://github.com/ARMmbed/mbed-os-example-cellular/tree/master)](https://github.com/ARMmbed/mbed-os-example-cellular/blob/master/main.cpp)
```

2020-03-18 15:46 UTC, jamesbeyond commented
Hi @AnotherButler, I updated this link, this PR is good to go

2020-03-18 15:46 UTC, jamesbeyond approved these changes

2020-03-18 18:26 UTC, AnotherButler approved these changes
Thanks for the PR 👍

2020-03-18 18:28 UTC, merged