Updated the flow control tutorial
ARMmbed/Handbook pull request #1287
Opened 2020-03-31 17:09 UTC by evedon

Some updates:
- Corrected several inaccuracies in tutorial.
- Busy wait is only mentionned at the beginning ; it is emphasized that if possible alternatives should be used.
- Introduced `ThisThread::sleep_for` and `thread_sleep_for` APIs.
- Renamed `Busy wait button` section to `Active polling button`.

2020-04-02 19:58 UTC, AnotherButler commented
I think this will pass Travis again if we rebase.

2020-04-03 20:35 UTC, AnotherButler commented
@iriark01 This is waiting on engineering review. It will then be ready for review.

2020-04-08 10:06 UTC, bulislaw approved these changes

2020-04-09 10:04 UTC, iriark01 requested changes

2020-04-09 10:04 UTC, iriark01 commented on docs/api/io/flow_control.md
> +<span class="tips">**Tip:** Busy wait is inefficient and should be avoided. </span>
```suggestion
<span class="tips">**Tip:** Busy wait is inefficient, and we recommend not using it. </span>
```

2020-04-09 10:04 UTC, iriark01 commented on docs/api/io/flow_control.md
> +A better alternative to busy wait is to suspend thread execution while waiting. You can use the `ThisThread::sleep_for` C++ API or `thread_sleep_for` C API.
```suggestion
A better alternative to busy wait is to suspend thread execution while waiting. Use:

 * For C++: The `ThisThread::sleep_for` API 
 * For C: The `thread_sleep_for` API.
```

2020-04-09 10:04 UTC, iriark01 commented on docs/api/io/flow_control.md
> +If you don't need the precision of a high-frequency timer/ticker, we recommend that you use LowPowerTimer/LowPowerTicker instead because this will allow the system to be put in deep sleep mode.
```suggestion
If you don't need the precision of a high-frequency timer or ticker, we recommend that you use LowPowerTimer or LowPowerTicker instead. This allows the system to be put in deep sleep mode.
```

2020-04-09 10:05 UTC, iriark01 commented
Should this go out to 6.0-alpha as well?

2020-04-09 10:49 UTC, evedon commented
> Should this go out to 6.0-alpha as well?

yes

2020-04-09 12:08 UTC, iriark01 commented
Merging; will cherry pick into alpha

2020-04-09 12:08 UTC, merged