Update UNITTESTS and Greentea test docs
ARMmbed/Handbook pull request #1364
Opened 2020-09-03 15:59 UTC by rajkan01

- Updated UNITTESTS and greentea test docs according to a new directory structure

2020-09-04 11:18 UTC, evedon requested changes

2020-09-04 11:18 UTC, evedon commented on docs/debugging-testing/testing/testing_greentea.md
> +You can run tests throughout Mbed OS and for your project's code. They are located under a special directory called `TESTS`of each library.
```suggestion
Greentea tests can be created anywhere in the Mbed OS directory structure or in your project's code. They are located under a special directory called `TESTS`. By convention, greentea tests for a specific Mbed OS library should be placed in a `TESTS` folder under that library. The `mbed-os/TESTS` folder is dedicated to integration or system tests.
```

2020-09-04 11:18 UTC, evedon commented on docs/debugging-testing/testing/testing_greentea.md
> +mbed-os/mylibrary/tests/TESTS/test_group/test_case_1
I would not change the example with `myproject`; it is still valid and it was clearer.

2020-09-04 11:18 UTC, evedon commented on docs/debugging-testing/testing/testing_greentea.md
> +In this example, `mylibrary` is like platform, drivers etc., and all the source files under the `test_case_1` directory are included in the test. The test build also includes any other source files f
Similarly, keep the original text.

2020-09-04 11:18 UTC, evedon commented on docs/debugging-testing/testing/testing_greentea.md
> +A test case is named by its position in your project's file structure. For instance, in the above example, a test case with the path `mylibrary/tests/TESTS/test_group/test_case_1` would be named `tes
Keep original.

2020-09-04 11:18 UTC, evedon commented on docs/debugging-testing/testing/testing_greentea.md
>  ### Building tests
Adding comment here for the rest of the file:
- Section Writing integration tests using host tests: update the location of host tests to `mbed-os/TESTS/host_tests` and sy that this directory should be created if it does not exist.
- Output extracts should be updated with new directory structure

2020-09-08 09:54 UTC, evedon commented
You missed some instances of `tests-mbedmicro-rtos-mbed-mail`. I'd suggest to run the actual commands and copy & paste the output.

2020-09-08 10:25 UTC, Elise-Kaminski commented
LGTM. I've just made some minor edits.

2020-09-08 11:04 UTC, evedon approved these changes

2020-09-08 12:51 UTC, Elise-Kaminski commented
Looks good. I reapplied the changes I had done.

2020-09-08 13:02 UTC, merged