mbed cli 2: Rename command line options
ARMmbed/Handbook pull request #1377
Opened 2020-11-20 15:40 UTC by jainvikas8

To ensure good usability with the Mbed CLI 2 the command line
options need to harmonize with the old Mbed CLI 1.

Therefore the following command options are changed by keeping the
existing functionality.

* `devices` to `detect`
* `init` to `new`
* `build` to `compile`
* `clone` to `import`

Further updated CMake minimum version requirement to 3.19.0

2020-11-20 16:49 UTC, Patater requested changes

2020-11-20 16:49 UTC, Patater commented on docs/tools/mbed_cli_2/use.md
>  - To get help for a specific command, use `mbed-tools <command> --help`. For example, for helping with listing connected devices (the `devices` command):
```diff
- For example, for helping with listing connected devices (the `devices` command)
+ For example, for helping with listing connected devices (the `detect` command)
```

2020-11-20 16:49 UTC, Patater requested changes

2020-11-20 16:49 UTC, Patater commented on docs/tools/mbed_cli_2/use.md
> +    mbedtools deploy <PATH>
Do we usually use `mbed-tools` or `mbedtools` in this document? Make everything consistent, without changing too many of them.

2020-11-20 17:31 UTC, jainvikas8 commented
Forced pushed to address comments from @Patater

2020-11-23 09:33 UTC, jainvikas8 commented
Please do not merge before - https://github.com/ARMmbed/mbed-tools/pull/112

2020-11-23 15:03 UTC, Patater approved these changes

2020-11-24 12:06 UTC, jainvikas8 commented
New Mbed CLI 2 release pending - 3.6.0

2020-12-01 10:24 UTC, Patater commented
Mbed CLI 2 4.0.0 is up on pypi

2020-12-01 12:09 UTC, merged