update GCC_ARM compiler supported to 10.3-2021.07
ARMmbed/Handbook pull request #1483
Opened 2021-09-06 08:41 UTC by saheerb

2021-09-06 08:49 UTC, donatieng requested changes
Thanks Saheer, one minor nit below:

2021-09-06 08:49 UTC, donatieng commented on docs/tools/tools_intro.md
> +| GNU Arm Embedded version 10 (9-2019-q4-major) | [GNU Arm Embedded version 10 (10.3-2021.07)](https://developer.arm.com/open-source/gnu-toolchain/gnu-rm/downloads) | `GCC_ARM` |
```suggestion
| GNU Arm Embedded version 10 (10.3-2021.07) | [GNU Arm Embedded version 10 (10.3-2021.07)](https://developer.arm.com/open-source/gnu-toolchain/gnu-rm/downloads) | `GCC_ARM` |
```

2021-09-06 08:51 UTC, jeromecoutant commented
Need to wait for updates in mbed-os repo ?

2021-09-06 08:54 UTC, donatieng commented
Indeed, prior to merging we need:
* https://github.com/ARMmbed/mbed-os/issues/14968
* https://github.com/ARMmbed/mbed-os/pull/15007

2021-09-06 08:56 UTC, donatieng approved these changes
@ChrisGooch-Arm let's wait for the above issue and PR to be in first, they we can merge this one

2021-09-06 09:31 UTC, 0xc0170 approved these changes

2021-09-06 09:35 UTC, 0xc0170 commented
Both of above will be most likely resolved within today, I'll keep an eye on both.

2021-09-21 11:00 UTC, ChrisGooch-Arm commented
@donatieng, @0xc0170  - is this ok to merge now or is there still a dependency on other things?

2021-10-05 12:25 UTC, 0xc0170 commented
Yes, please lets merge. All was resolved for the Mbed OS release in September.

2021-10-21 07:46 UTC, 0xc0170 commented
@ChrisGooch-Arm can we merge this, its needed.

2021-10-21 09:10 UTC, merged