Cellular docs updated
ARMmbed/Handbook pull request #914
Opened 2019-01-11 08:12 UTC by AriParkkila

Cellular docs updated for Mbed OS 5.12.

Porting guide need to be finished later.

2019-01-11 09:14 UTC, melwee01 requested changes
Bit too much passive voice for my taste, but I don't know that we can afford to be that picky.

2019-01-11 09:14 UTC, melwee01 commented on docs/api/networkinterfaces/CellularInterface.md
> +- [Cellular overview](../reference/cellular.html) describes more details about the cellular architecture and its usage.
describes cellular architecture and its usage in more detail.

2019-01-11 09:14 UTC, melwee01 commented on docs/porting/connectivity/CellularInterface.md
> +### Adding cellular on Mbed OS target
on an Mbed OS target

2019-01-11 09:14 UTC, melwee01 commented on docs/porting/connectivity/CellularInterface.md
>  You need to specify in [CellularTargets.h](https://os.mbed.com/docs/development/mbed-os-api-doxy/_cellular_targets_8h_source.html) the `<manufacturer-module>` that is mounted on your board.
~that is~ mounted

2019-01-17 22:04 UTC, AnotherButler reviewed
Thanks for the PR. I left some comments asking about links I can't get to work. I think maybe that's on the Doxygen/code end?

2019-01-17 22:04 UTC, AnotherButler commented on docs/api/networkinterfaces/CellularInterface.md
> +<h2 id="cellular-api">Cellular API</h2>
Query: Why did we add "API" here?

2019-01-17 22:04 UTC, AnotherButler commented on docs/api/networkinterfaces/CellularInterface.md
> +<span class="images">![](https://os.mbed.com/docs/development/mbed-os-api-doxy/class_cellular_interface.png)<span>CellularInterface class hierarchy</span></span>
Query: Where should this link go? I don't see any class in the Doxygen called "CellularInterface".

2019-01-17 22:04 UTC, AnotherButler commented on docs/api/networkinterfaces/CellularInterface.md
> +The [CellularInterface](https://os.mbed.com/docs/development/mbed-os-api-doxy/class_cellular_interface.html) class provides a C++ API for connecting to the internet over a Cellular device.
Query: Where should this link go? It 404s for me.

2019-01-17 22:04 UTC, AnotherButler commented on docs/api/networkinterfaces/CellularInterface.md
> +### CellularInterface class reference
Do we have a class called CellularInterface? I can't find it in the Doxygen.

2019-01-17 22:04 UTC, AnotherButler commented on docs/api/networkinterfaces/CellularInterface.md
> +[![View code](https://www.mbed.com/embed/?type=library)](https://os.mbed.com/docs/development/mbed-os-api-doxy/class_cellular_interface.html)
Where should this link go? It 404s for me.

2019-01-17 22:04 UTC, AnotherButler commented on docs/porting/connectivity/connectivity.md
> +- [CellularInterface](https://os.mbed.com/docs/development/mbed-os-api-doxy/class_cellular_interface.html).
Query: Where should this link go? It 404s for me.

2019-01-17 22:04 UTC, AnotherButler commented on docs/reference/technology/connectivity/cellular.md
> +- Quick start with Mbed Enabled boards.
Is the quick start a key features of the Mbed OS cellular APIs? That doesn't sound right to me.

2019-01-17 22:04 UTC, AnotherButler commented on docs/reference/technology/connectivity/cellular.md
> +Many Mbed Enabled boards already support cellular connectivity. Because Mbed OS is an open source platform, developers can enable support for new cellular boards with our adaptation framework. Please
Please change link to "(../porting/cellular-module-porting.html)", so it's not tied to a specific version.

2019-01-17 22:04 UTC, AnotherButler commented on docs/reference/technology/connectivity/cellular.md
> +A network interface instantiated directly or using calls such as `CellularInterface::get_default_instance()` or `CellularContext::get_default_instance()` is initially unconfigured. You can call `Netw
When we say "see nsapi JSON configuration", is there a link we can add?

2019-01-17 22:04 UTC, AnotherButler commented on docs/reference/technology/connectivity/cellular.md
> +If Mbed OS target board has an on-board cellular device then the cellular framework uses that by default when calling `get_default_instance()`. The default cellular device instance can be overridden
"If an Mbed ..."

2019-01-18 08:41 UTC, AriParkkila commented on docs/api/networkinterfaces/CellularInterface.md
> +<h2 id="cellular-api">Cellular API</h2>
It's to indicate that this page is for API developers, I guess that's right..?

2019-01-18 08:41 UTC, AriParkkila commented on docs/api/networkinterfaces/CellularInterface.md
> +<span class="images">![](https://os.mbed.com/docs/development/mbed-os-api-doxy/class_cellular_interface.png)<span>CellularInterface class hierarchy</span></span>
Mbed OS 5.12 will rename CellularBase => CellularInterface.

2019-01-18 08:42 UTC, AriParkkila commented on docs/api/networkinterfaces/CellularInterface.md
> +The [CellularInterface](https://os.mbed.com/docs/development/mbed-os-api-doxy/class_cellular_interface.html) class provides a C++ API for connecting to the internet over a Cellular device.
See above.

2019-01-18 08:42 UTC, AriParkkila commented on docs/api/networkinterfaces/CellularInterface.md
> +### CellularInterface class reference
See above.

2019-01-18 08:42 UTC, AriParkkila commented on docs/api/networkinterfaces/CellularInterface.md
> +[![View code](https://www.mbed.com/embed/?type=library)](https://os.mbed.com/docs/development/mbed-os-api-doxy/class_cellular_interface.html)
See above.

2019-01-18 08:42 UTC, AriParkkila commented on docs/porting/connectivity/connectivity.md
> +- [CellularInterface](https://os.mbed.com/docs/development/mbed-os-api-doxy/class_cellular_interface.html).
See above.

2019-01-18 08:48 UTC, AriParkkila commented on docs/reference/technology/connectivity/cellular.md
> +- Quick start with Mbed Enabled boards.
Could be written also that "Supports Mbed Enabled boards"..?

2019-01-18 17:58 UTC, AnotherButler commented
@AriParkkila Thanks for clarifying. Because this depends on code that hasn't merged yet, I'm going to add a code dependency label. Could you please link to the relevant mbed-os PR?

2019-02-08 20:17 UTC, AnotherButler commented
@AriParkkila  or @mirelachirica Could one of you please let me know which code PR (if there is one) this is waiting for? Also, could you please resolve the merge conflicts?

2019-02-11 06:42 UTC, AriParkkila commented
@AnotherButler PR has not been made yet. This time we documented it before anything was implemented, so I guess we are learning :) I will rebase and update this when PR is ready.

2019-02-18 10:15 UTC, AriParkkila commented
@AnotherButler PR for the CellularInterface class https://github.com/ARMmbed/mbed-os/pull/9746

2019-02-20 17:24 UTC, merged