Delete table from build_rules.md
ARMmbed/Handbook pull request #943
Opened 2019-02-07 14:47 UTC by AnotherButler

Delete table for test.

2019-02-07 14:51 UTC, iriark01 requested changes
I left a few comments.

2019-02-07 14:51 UTC, iriark01 commented on docs/reference/build_rules.md
>  Mbed OS build tools determine the type of source file found based on the file's extension. The following table lists all files used in a build:
I can leave a comment

2019-02-07 14:51 UTC, iriark01 commented on docs/reference/build_rules.md
>  ### Label directories
I'll add another comment to be annoying

2019-02-07 14:53 UTC, iriark01 commented on docs/reference/build_rules.md
This will email Amanda

2019-02-07 14:53 UTC, iriark01 requested changes

2019-02-07 14:53 UTC, iriark01 commented on docs/reference/build_rules.md
Won't email her yet

2019-02-07 14:54 UTC, iriark01 approved these changes
This is cool

2019-02-15 21:59 UTC, AnotherButler commented
Closing because this was an example in a demo

2019-02-15 21:59 UTC, closed without merging